### ISSUE TITLE
Signout support

### ISSUE THREAD

**Issue by EmlynWill** [eclipse/che-che4z-explorer-for-endevor#110]
I would like the Edit feature to include signout support.
If an Endevor system requires signout in the system definition
 SIGN-IN/SIGN-OUT OPTIONS:          
   ACTIVATE OPTION:          Y (Y/N)
then retrieve the element for edit with signout. Whether retrieve with signout is used or not should be transparent to the user.
If the element is already signed out to another user then offer the option of overriding the signout.

The current version of the edit feature does not work for us because the add fails saying that the element is not signed out.

**Comment by jellypuno** [comment]
Thank you @EmlynWill

**Comment by nickImbirev** [comment]
We can also provide support for over-sign out of the elements:

- We could allow over-signout (if upload fails, user can click "Sign-out again" or sth. Then upload proceeds)
- We could check if Endevor has "sign-out required" setting enabled. If so, we automatically over-signout for the user, and don't prompt them (can be activated with additional VSCode setting)
