### ISSUE TITLE
Error files.encoding generate ï¿½ or � and that should be £

### ISSUE THREAD

**Issue by jellypuno** [eclipse/che-che4z-explorer-for-endevor#111]
We have an issue when we browse or retrieve an element via Visual Studio Code and it change some character like the "£". 
Visual Studio Code convert it on ï¿½ or � 

Problem: E4E is currently supporting UTF-* encoding only
Solution: Have the ability to support other encoding

**Comment by RedGoldPhoenix** [comment]
Hello 
I had a meeting with Vít Gottwald and Michal Vasak about this topic.
With the System Team Support we changed the parameter on the ENDEVOR.cfg
We replaced : CharacterSet="ISO8859-1" and LFSEncoding="ISO8859-1" by CharacterSet="UTF-8" and LFSEncoding="UTF-8"
Not we have no code page issue.
Thanks a lot for your support
You can close this ticket
Have a great day and enjoy your week-end
Best Regards

**Comment by jellypuno** [comment]
Thank you for the update @RedGoldPhoenix . I'll close this issue
