### ISSUE TITLE
Generate  issue with the plugin Broadcom Explorer for Endevor

### ISSUE THREAD

**Issue by jellypuno** [eclipse/che-che4z-explorer-for-endevor#112]
E4E is generating in place. If I have an element in Stage 2 and tried to generate it, I would expect that it would be generated and replaced in Stage 1.

**Comment by nickImbirev** [comment]
This issue will/can be resolved within the https://github.com/eclipse/che-che4z-explorer-for-endevor/issues/114

**Comment by jellypuno** [comment]
Possibly Handled in Sync Research
