### ISSUE TITLE
Full text search across the all elements in Endevor - Enhancement request

### ISSUE THREAD

**Issue by radecek9787** [eclipse/che-che4z-explorer-for-endevor#12]
When using explorer for Endevor, I can browse all the elements defined in any particular Endevor system. However, when I work on resolving any customer case, I need to search for specific string across all the elements in the respective Endevor system to find all elements containing the searched string. This is not currently possible in explorer for Endevor so I need to run a batch job, executing program NDVRC1 and find the search results in the output of the job.

**Comment by zimlu02** [comment]
Unfortunately, this functionality is not supported by Endevor API so that our extension cannot extend it. Achieving the requested result by submitting the job would be very cumbersome in case of Explorer for Endevor. As per our discussion, I suggest opening an enhancement request for Zowe Explorer.
