### ISSUE TITLE
Show E4E version in VSCode OUTPUT on the startup

### ISSUE THREAD

**Issue by nickImbirev** [eclipse/che-che4z-explorer-for-endevor#121]
We should show the git commit hash in VSCode, so that reviewers can tell what version of the code they are using...and also so we can help customers debug more effectively.

Command `git rev-parse HEAD` may help - it outputs commit hash

**Comment by anton-brezina** [comment]
We could have a text file as part of the repository which content would be updated during the packaging to contain the output of the `git rev-parse HEAD`.

**Comment by anton-brezina** [comment]
@jellypuno if we have time while waiting for something anybody can do this.
If we don't get to it anytime soon you might want to set a priority on this and actually plan it.
