### ISSUE TITLE
Research: how to stop storing credentials in tree nodes

### ISSUE THREAD

**Issue by nickImbirev** [eclipse/che-che4z-explorer-for-endevor#123]
We should research how to stop storing creds in the tree nodes and in passed URIs

**Comment by jellypuno** [comment]
Easiest solution is to keep the name of the profile in the session and every time we call a function (e.g. generate, view etc) the function to read the profile information will be called. 

Concern: 
- Performance Test. Comparison between the current solution and to the new one.

Research:
- Check if there's an API to get the profile information by name. If we have this API then we do not need a performance test.

**Comment by nickImbirev** [comment]
I finally investigated this issue: we can use AuthProvider API to avoid storing any sensitive data in the treeNode or in the URI. We can also implement more interesting and complicated Auth Provider for the Profiles SCS support and for the adaptation of the ZE APIs.

**Comment by nickImbirev** [comment]
we can also add the support for the tokens easily for the #129 issue in the [same way](https://github.com/eclipse/che-che4z-explorer-for-endevor/issues/123#issuecomment-1016424408)
