### ISSUE TITLE
Timeout/cancellation for long operations 

### ISSUE THREAD

**Issue by nickImbirev** [eclipse/che-che4z-explorer-for-endevor#126]
As a user, I would like to have ability to set timeout for long operations (or even set default timeout value in settings)

**Comment by anton-brezina** [comment]
Original ideas of a long operation:
- retrieve operations 
- multiple selects
- searching for elements

Alternative would be to have a notification and/or the ability to cancel the long running operation.
What if the user will miss the notification?
Can we just close the notification?
Consider the long running fetching element (could be addressed by having the response chunked).
Would a scheduler work to solve this issue?

Decision:
1. We should have a list of concrete operations on which to implement this.
2. We should agree on the approach (i.e. with the "cancel" button).

**Comment by roman-kupriyanov** [comment]
By @VitGottwald:
> Relates to https://github.com/eclipse/che-che4z-explorer-for-endevor/issues/183. Perhaps better than having timeouts would be the ability to cancel the operation.

**Comment by nickImbirev** [comment]
@roman-kupriyanov @zdmullen do you think we can mark this issue as completed after the cancellation option implementation for the tree searching?

The issue itself is pretty vague, so, I would propose to create more specific instead, with particular cancellation use cases. What do you think?

**Comment by roman-kupriyanov** [comment]
I personally have nothing against closing it. Do we only have cancellable commands themselves left?

**Comment by nickImbirev** [comment]
> I personally have nothing against closing it. Do we only have cancellable commands themselves left?

Yep, only the commands, but we can create separate issues and handle them separately.

**Comment by roman-kupriyanov** [comment]
> Yep, only the commands, but we can create separate issues and handle them separately.

Agreed, makes sense 😃

**Comment by nickImbirev** [comment]
closed by https://github.com/eclipse/che-che4z-explorer-for-endevor/pull/282
