### ISSUE TITLE
Change regression error during element uploading

### ISSUE THREAD

**Issue by nickImbirev** [eclipse/che-che4z-explorer-for-endevor#128]
When I upload edited element into Endevor, I sometimes get the error message: `SMGR123C 99% PRIOR INSERTS DELETED AND/OR 01% PRIOR DELETES RE-INSERTED`

It seems, like it is indicated, that I'm modifying the code, that was modified in the previous version. Maybe we can suppress this message somehow? Or provide ability for users to suppress it, if they feel confident about what they are doing...

**Comment by jellypuno** [comment]
Show warning instead of an error

**Comment by nickImbirev** [comment]
resolved within #181 PR
