### ISSUE TITLE
Leftover .e4e temporary folder could get "stuck"

### ISSUE THREAD

**Issue by nickImbirev** [eclipse/che-che4z-explorer-for-endevor#135]
We should make sure the `tempFiles` folder with the old name is properly deleted (maybe with temp files migration), If the user changes the name of it in settings.

**Comment by nickImbirev** [comment]
possible solution: This will be automatically resolved, once VSCode guys will deliver new API for workspace file handling. We will migrate our codebase into it.

**Comment by VitGottwald** [comment]
Can you add a link to the discussion/docs about workspace file API @nickImbirev ?

**Comment by nickImbirev** [comment]
> Can you add a link to the discussion/docs about workspace file API @nickImbirev ?

Hey, yep, sure. Here is the [link](https://github.com/microsoft/vscode/issues/15178).

I think, the issue will go automatically, once we will be able to specify certain callbacks for closing/saving specific documents.

Now, we are getting one event for saving every document in the workspace, so we have to verify, that it was/was not 'edited' document all the time, which lead us to the requirement: always keep the 'edited' elements folder name and compare it with incoming values, which is a root of the problem.

**Comment by nickImbirev** [comment]
btw, right after writing the comment above, I realised, that we can validate the URI of the saved/closed document and ignore the file path at all. 

Now, URI validation is our rough check to see, if we need to trigger the commands at all, so we can resolve this issue with existing API, if we will enhance validation with `io-ts` types (for example).

**Comment by nickImbirev** [comment]
will be solved within #263

**Comment by nickImbirev** [comment]
resolved in the https://github.com/eclipse/che-che4z-explorer-for-endevor/pull/272 (1.2.0 release)
