### ISSUE TITLE
Failed to fetch existing services because of: Failed to create Profile manager - ENDEVOR

### ISSUE THREAD

**Issue by EmlynWill** [eclipse/che-che4z-explorer-for-endevor#136]
One of our users got this error when creating a new Endevor profile
"Failed to fetch existing services because of: Failed to create Profile manager - ENDEVOR"

Steps he took to create it.

Create a new Endevor profile by clicking on the "+" icon next to "EXPLORER FOR ENDEVOR" at the top left of the Endevor Explorer view
•	Click on "+ Create a New Endevor Profile" underneath the text input box that appears

![Failure](https://user-images.githubusercontent.com/75491884/124633447-31a35c80-de7d-11eb-96f5-dda769fafe75.png)

**Comment by nickImbirev** [comment]
Hey! This message indicates, that the user does not have an endevor-cli plugin installed, which is a requirement for the released version of E4E.

I can suggest to [install](https://docs.zowe.org/stable/user-guide/cli-installplugins.html) the CLI plugin for [Endevor](https://techdocs.broadcom.com/us/en/ca-mainframe-software/devops/ca-brightside/3-0/zowe-cli/available-cli-plug-ins/ca-endevor-scm-plug-in-for-zowe-cli.html) as an urgent solution, or just wait for a few days until the updated version of E4E will be released, where we don't require CLI anymore.

**Comment by EmlynWill** [comment]
I knew that! I really should stop taking time off work. Thank you for reminding me. 
Not needing Zowe CLI will be great, we will wait for the next version.
