### ISSUE TITLE
Collapse all nodes after browser refresh

### ISSUE THREAD

**Issue by zimlu02** [eclipse/che-che4z-explorer-for-endevor#15]
When any node in Explorer for Endevor is expanded and the page is refreshed, the credentials prompt pops-up even when the user works in a different tab or extension. 

**Steps to reproduce:**

1. Login to E4E and open any node (Filters or Maps)
2. Refresh the page
3. Credentials dialog pops-up

**Desired behaviour:**
After browser refresh, all nodes collapse so that no login is required.

<img width="225" alt="Screenshot 2020-01-30 at 12 10 34" src="https://user-images.githubusercontent.com/38490125/73470322-fe0afb80-4387-11ea-9523-c759e00406b7.png">

**Comment by jellypuno** [comment]
This is already implemented in v0.12.1. Can you please try again?

**Comment by zimlu02** [comment]
hmmm... it is still bit there. You have to collapse the node manually, otherwise on refresh it requires credentials even if you currently work in a different connection.
However now I consider the user experience impact very low. It can be also considered as a desired UX behaviour, so I am OK to close this ticket.
