### ISSUE TITLE
Timeout for long operations

### ISSUE THREAD

**Issue by jellypuno** [eclipse/che-che4z-explorer-for-endevor#156]
As a user, I would like to have ability to set timeout for long operations (or even set default timeout value in settings)

VSCode may already have an automated timeout period. Does the user really need to set/change this time personally?

**Comment by VitGottwald** [comment]
Relates 183. Perhaps better than having timeouts would be the ability to cancel the operation.

**Comment by roman-kupriyanov** [comment]
Close this duplicated one, because of another - #126.
