### ISSUE TITLE
Collapse the node when login is cancelled by the user

### ISSUE THREAD

**Issue by zimlu02** [eclipse/che-che4z-explorer-for-endevor#16]
**Steps to reproduce:**

1. Select E4E extension and expend a node (Filters or Maps)
2. Cancel the login (using ESC key)
3. Node stays expanded
4. After a page refresh it requires the login again...

**Desired behavior:**
When the user cancels the login, the node collapses so that after refresh it does not require login.

**Comment by jellypuno** [comment]
@zimlu02 Can we close this issue?

**Comment by zimlu02** [comment]
yes, thanks
