### ISSUE TITLE
Ungainly recovery from mistyped userid or password

### ISSUE THREAD

**Issue by slackHer** [eclipse/che-che4z-explorer-for-endevor#174]
If I accidentally mistype my password when opening a location profile,  I get a message saying I can't signon. Then, I have to restart VS Code in order to get the prompt for userid/password. Is there a way to avoid the VS Code restart or a manual edit/refresh of the profile?

**Comment by nickImbirev** [comment]
closed by https://github.com/eclipse/che-che4z-explorer-for-endevor/pull/282
