### ISSUE TITLE
Discard compare elements is not closing active edit session since VSCode 1.61 version

### ISSUE THREAD

**Issue by nickImbirev** [eclipse/che-che4z-explorer-for-endevor#175]
**Prerequisite:** when users edit an element - they may have conflicts between E4E and Endevor element contents. This is handled by compare feature, with ability to compare element versions and upload the right one, with all required changes.
There are two options to select in compare session: apply changes (try to upload merged content) and discard changes (close compare dialog and edit session - basically, discard local progress).

**Before 1.61 VSCode version:** when users click `discard` button - they have compare session and edited element closed.

**After 1.61 VSCode version:** when users click `discard` button - they have compare session closed, **but the edited element is still active in the window.**

Do we need to save the existing behaviour or we can consider this as a bug?

**Comment by anton-brezina** [comment]
In general we claim to support the latest VSCode version.

**Comment by anton-brezina** [comment]
The described behaviour is not considered to be an issue and we are leaning towards leaving this as is. However we have two other issues discovered related to this:
- In 1.62 we do not have a discard button
- we should revisit our UX

**Comment by nickImbirev** [comment]
I'm closing this issue after the discussion
