### ISSUE TITLE
support for elements long names

### ISSUE THREAD

**Issue by dezkolakatus** [eclipse/che-che4z-explorer-for-endevor#176]
add support for endevor elements long names, so they can be directly uploaded to Endevor

**Comment by EmlynWill** [comment]
Editing USS elements is one of the areas that VSCode does better than the mainframe editor. It would be great to have this functionality in the Endevor explorer so That i do not have to use the long retrieve/edit/add process.

**Comment by nickImbirev** [comment]
Thank you for submitting this! We actually have a [duplicate](https://github.com/eclipse/che-che4z-explorer-for-endevor/issues/7), so, I'm gonna close this particular item and we will try to implement an enhancement in the context of the initial issue.
