### ISSUE TITLE
Reject unauthorized value not picked up from the BASE profile

### ISSUE THREAD

**Issue by EmlynWill** [eclipse/che-che4z-explorer-for-endevor#184]
Version 0.14.0

Warning message "There is no reject unauthorized specified in the Endevor profile, default value: true will be used instead"

I have "rejectUnauthorized: false" set in my base profile, but no rejectUnauthorized: value in my Endevor profile.

N.B. The extension does work, there is no issue other than the warning message. Userid and password are successfully picked up from my base profile.

**Comment by nickImbirev** [comment]
resolved in the https://github.com/eclipse/che-che4z-explorer-for-endevor/pull/272 (1.2.0 release)
