### ISSUE TITLE
Confusing message when credentials are wrong

### ISSUE THREAD

**Issue by VitGottwald** [eclipse/che-che4z-explorer-for-endevor#190]
When expanding the elements tree with an incorrect password, I receive `Unable to fetch any valid element from Endevor` message. Looking into the diagnostic output says no more. This is confusing.

It would be great if I got a specific error message saying my credentials are wrong.

**Comment by VitGottwald** [comment]
<img width="460" alt="Screenshot 2021-11-30 at 17 16 22" src="https://user-images.githubusercontent.com/19686979/144085338-e60f1b48-834e-49b7-9d97-b0b672fde106.png">

**Comment by slavek-kucera** [comment]
I might be a good idea to also block all requests until the user gives a green light to prevent lockouts.

**Comment by nickImbirev** [comment]
can be considered with #119

**Comment by roman-kupriyanov** [comment]
Thanks @nickImbirev for assigning! I am working on it..

**Comment by nickImbirev** [comment]
closed by https://github.com/eclipse/che-che4z-explorer-for-endevor/pull/282
