### ISSUE TITLE
Make bug/issue reporting slightly easier

### ISSUE THREAD

**Issue by nickImbirev** [eclipse/che-che4z-explorer-for-endevor#192]
I know, that we have a problem with community involvement. Maybe we can attract users to our repo by simplifying our bug/issues reporting process?

I propose to have a separate flag or any other icon in the main extension panel (in a very very visible place), where people can click and submit an issue in our GH repository relatively quickly. We can create a filled template for them and they might want to submit their feedback immediately, without going to their management or in their/our CMS.

What do you all think?

**Comment by roman-kupriyanov** [comment]
I think this is a great idea! Thanks for proposing @nickImbirev 😃

**Comment by nickImbirev** [comment]
resolved in the https://github.com/eclipse/che-che4z-explorer-for-endevor/pull/272 (1.2.0 release)
