### ISSUE TITLE
[Readme] Signout element gif is not visible

### ISSUE THREAD

**Issue by nickImbirev** [eclipse/che-che4z-explorer-for-endevor#196]
We have a small issue with the [signout element gif](https://github.com/eclipse/che-che4z-explorer-for-endevor#sign-out).

Apparently, it is not visible because of the [typo](https://github.com/eclipse/che-che4z-explorer-for-endevor/blob/77462963dc0238de20a12f859caf75a6c76eaecc/README.md?plain=1#L289) in the gif file reference.

**Comment by Y-u-n-u-s** [comment]
Hey i am a beginner, i am not able to properly understand this issue can you help me out :(

**Comment by nickImbirev** [comment]
> Hey i am a beginner, i am not able to properly understand this issue can you help me out :(

Hey! The issue is very small, actually, if you take a look into our [README](https://github.com/eclipse/che-che4z-explorer-for-endevor#explorer-for-endevor) in the main repository page, you will notice, that one [image](https://github.com/eclipse/che-che4z-explorer-for-endevor#sign-out) is not visible there (there is a default image icon instead). Probably, the link to the image has been broken, so we just need to fix it :)

Does it make sense?

**Comment by roman-kupriyanov** [comment]
Taking this one 😃
