### ISSUE TITLE
Issue when using https

### ISSUE THREAD

**Issue by MikeBauerCA** [eclipse/che-che4z-explorer-for-endevor#20]
We recently changed the protocol of the Endevor web service to https. After making this change, we are no longer able to use the Explorer for Endevor. When entering a new connection, a message pops up that reads `Waiting for https://host:port to respond.`

I can successfully reach the service via the CA Endevor SCM Plug-in for Zowe CLI. When using the CLI plug-in, I do specify `--reject-unauthorized false`. The Explorer for Endevor does not present me with such an option so that may be related.

Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:25.463Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-88-generic

Explorer for Endevor v0.9.1

**Comment by zdmullen** [comment]
Hey Mike,

This issue is now fixed with the upcoming release of 0.10.0. You'll be able to use https connections, and in general follow the flow for creating a profile that you are familiar with from Zowe Explorer. I'll keep you posted as to when we release.
