### ISSUE TITLE
Discard changes editor/title command does not close the initially edited element

### ISSUE THREAD

**Issue by nickImbirev** [eclipse/che-che4z-explorer-for-endevor#214]
**The legend:** currently, the user can have version conflicts, during the uploading of an element back to Endevor after editing it (using the `edit` context-menu item). E4E will show the conflict resolution dialog in this case with the two possible options (accept the local changes and discard the local changes)

**AS IS:** when the user clicks on the discard local changes icon in the editor - they have all the local changes for the element removed, but the editor for the initially edited element is still opened, even the element local version is deleted

**TO BE:** when the user clicks on the discard local changes icon in the editor - they should have all the local changes removed with the local version of the element and all the editors with active edit session for the same element should be closed

**Comment by nickImbirev** [comment]
related to the possible bug in VSCode (since version 1.64 or even earlier): https://github.com/microsoft/vscode/issues/142629

**Comment by roman-kupriyanov** [comment]
Did you try 1.64.1 vscode patch with this?

**Comment by nickImbirev** [comment]
> Did you try 1.64.1 vscode patch with this?

Yeah, regretfully it is still there :(
