### ISSUE TITLE
Change the generateElement successful message

### ISSUE THREAD

**Issue by nickImbirev** [eclipse/che-che4z-explorer-for-endevor#219]
I propose to change the generateElement command successful message from the two separate messages: `Generate successful` and the following one: `Would you like to see the listing?` to one message: `The element XYZ is successfully generated. Would you like to see the listing?` instead.

AS IS behaviour:
<img width="587" alt="Screenshot 2022-02-18 at 13 24 55" src="https://user-images.githubusercontent.com/74672982/154682569-6cbe7766-6c43-4b59-b562-05ffe690e60b.png">

initially proposed by @roman-kupriyanov

**Comment by roman-kupriyanov** [comment]
I will take this one 😉
