### ISSUE TITLE
Signout/override signout errors are a bit confusing in the extension Output

### ISSUE THREAD

**Issue by nickImbirev** [eclipse/che-che4z-explorer-for-endevor#223]
AS IS: Today, E4E shows very user friendly notifications for the signout/override signout functions, but the messages in the extension Output are a bit hard to understand, because they are about retrieving.

TO BE: E4E should have similar message patterns for the notification and in the OUTPUT, because it is really hard to understand, how retrieve and signout are connected to each other from the big blob of logs :(

**Comment by uzuko01** [comment]
I will go through the output messages.

**Comment by nickImbirev** [comment]
this one is addressed within the 1.3.0
