### ISSUE TITLE
Support to remove the location/service profiles from the disk

### ISSUE THREAD

**Issue by nickImbirev** [eclipse/che-che4z-explorer-for-endevor#238]
Right now, the users can only hide profiles from the tree (remove them from the `settings.json` file).

It would be nice to have a context-menu item to remove the profiles completely, not just hide them.

**Comment by roman-kupriyanov** [comment]
Taking this one 😉

**Comment by nickImbirev** [comment]
resolved in the https://github.com/eclipse/che-che4z-explorer-for-endevor/pull/272 (1.2.0 release)
