### ISSUE TITLE
Specify workspace before creating repository.

### ISSUE THREAD

**Issue by mfsysprog** [eclipse/che-che4z-explorer-for-endevor#24]
I've installed the explorer for endevor plugin in visual studio code version 1.45.0.
The first thing I tried after it was installed is to create a new connection. But when I click that, the error message 'Specify workspace before creating repository' is shown. Can you guide me to what I'm suppost to do in this case?

**Comment by zdmullen** [comment]
Hi! With respect to your issue, ensure that you have started a new file, or opened a file or folder in Visual Studio Code before you begin using Explorer for Endevor. This begins the workspace, after which you can then create a connection in Explorer for Endevor.

**Comment by mfsysprog** [comment]
Yes, thank, I had just figured that out. After adding a folder to the workspace it works.

**Comment by mfsysprog** [comment]
I had already selected a workspace, but never added a file or a folder to it.

**Comment by mfsysprog** [comment]
Thanks for the fast reply, I will have to figure out if we have the other prerequisites in place now :-)

**Comment by zdmullen** [comment]
No problem. Keep us updated on your progress! We are on Slack, as you probably saw from the readme, and can answer any questions you have there as well.
