### ISSUE TITLE
An unexpected 'BASE STATEMENTS DELETED...' error during the element changes uploading

### ISSUE THREAD

**Issue by nickImbirev** [eclipse/che-che4z-explorer-for-endevor#241]
**The use case description:**
The user started an edit session for an element. They modified the element a lot, maybe even completely rewrote it from scratch. The user wants to upload the element changes back to Endevor (by pressing CTRL/CMD+S).

**AS IS:** the user gets an error, that the element was not uploaded (SMGR124C message code). The editor with the element stays opened, but the element content became uploaded, the element level and fingerprint were updated on the Endevor side.

**TO BE:** the element should be uploaded to Endevor successfully, the element editor should be closed.

**Comment by roman-kupriyanov** [comment]
I will take this one 😃

**Comment by nickImbirev** [comment]
closed by https://github.com/eclipse/che-che4z-explorer-for-endevor/pull/282
