### ISSUE TITLE
Show map path for a location profile hover

### ISSUE THREAD

**Issue by VitGottwald** [eclipse/che-che4z-explorer-for-endevor#244]
When a user hovers over the location profile in endevor tree view, display a tool tip with the target location path of the profile like `instance/env/sys/sub/type`. Use asterisk for unspecified pieces.

**Comment by nickImbirev** [comment]
resolved in the https://github.com/eclipse/che-che4z-explorer-for-endevor/pull/272 (1.2.0 release)
