### ISSUE TITLE
The element does not appear in the tree properly, in case it exists in multiple states within one elements tree

### ISSUE THREAD

**Issue by nickImbirev** [eclipse/che-che4z-explorer-for-endevor#246]
_Can be solved only within: #113_

**The use case:** 
The user has a search location profile defined with a subsystem wildcard (they are working on two features at the same time within one system). Their simplified Endevor map looks like this:
Feat1: DEV/1/SYS1/SBS1 -> PROD/1/SYS1/SBS
Feat2: DEV/1/SYS1/SBS2 -> PROD/1/SYS1/SBS

They also have an element (ELM1) in the PROD/1/SYS1/SBS. They want to modify this element in both of the features.

The user fetches the elements in the E4E using the search location profile, specified above. The user expands the SYS1/SBS2  (feature 1) node and finds the element ELM1 in the `map` folder. They start an edit session for the element and upload the element changes to their feature 1 sandbox (DEV/1/SYS1/SBS1).

**AS IS:** The user expands their feature 2 sandbox E4E tree node (DEV/1/SYS1/SBS2) and it does not contain the ELM1 from PROD/1/SYS1/SBS.

**TO BE:** The user expands their feature 2 sandbox E4E tree node (DEV/1/SYS1/SBS2) and it should contain the ELM1 from PROD/1/SYS1/SBS, even, if the ELM1 is already in feature 1 sandbox (DEV/1/SYS1/SBS1), because these sandboxes are on the same level in the Endevor map.

**Comment by VitGottwald** [comment]
Let's discuss this further on our call.

**Comment by VitGottwald** [comment]
My guess is that if we consider this a _but_, it will also be present in quick edit, I will check.

**Comment by VitGottwald** [comment]
Quick Edit returns first found elements for both subsystems. We should compare this to what Web services return and follow up.

**Comment by nickImbirev** [comment]
connected to #113

**Comment by nickImbirev** [comment]
closed by https://github.com/eclipse/che-che4z-explorer-for-endevor/pull/282
