### ISSUE TITLE
Sort objects when creating a filter

### ISSUE THREAD

**Issue by zdmullen** [eclipse/che-che4z-explorer-for-endevor#25]
As a user, I'd like to be able to sort the objects after I've created a filter. As an example, I have a lot of "No source" elements in my Endevor sandbox and want to be able to see only the edited components at the top of the list.   

Right now, the extension shows all elements, but I cannot retrieve "No source" elements because it only displays the error "C1G0208 ELEMENT NOT FOUND".

**Comment by jellypuno** [comment]
This is already implemented in v0.12.1
