### ISSUE TITLE
Initial tree refresh causes another redundant tree refresh

### ISSUE THREAD

**Issue by roman-kupriyanov** [eclipse/che-che4z-explorer-for-endevor#256]
Currently, if the user opens the location profile for the first time, underlyingly it causes a refresh of the tree process twice. Usually it is not visible and does not affect the user anyhow, but in the case of receiving the elements or Endevor map structure fetching errors, it shows the error twice (and it takes some time for the second unnecessary subsequent request).

**Comment by uzuko001** [comment]
I am looking into it, thanks for creating the issue @roman-kupriyanov

**Comment by nickImbirev** [comment]
resolved in the https://github.com/eclipse/che-che4z-explorer-for-endevor/pull/272 (1.2.0 release)
