### ISSUE TITLE
Opening of the one location profile causes refresh for another

### ISSUE THREAD

**Issue by roman-kupriyanov** [eclipse/che-che4z-explorer-for-endevor#257]
Steps to reproduce:

1. Create an invalid location profile (for example, for nonexistent location somewhere).
2. Try to open it and get an error.
3. Create a successful profile.
4. Try to open it and notice that the invalid profile is tried to be re-request as well.

**Comment by zdmullen** [comment]
This should be covered by the effort that we make on simplifying the logic of the requests.

**Comment by nickImbirev** [comment]
this one is covered by the 1.3.0
