### ISSUE TITLE
Retrieve functions not working with Bridge for Git repository

### ISSUE THREAD

**Issue by zdmullen** [eclipse/che-che4z-explorer-for-endevor#26]
When I have a synchronized repository from Bridge for Git open in my editor and try to retrieve an element or retrieve with dependencies, the process runs but no files open in my editor and don't appear anywhere. 

Can you ensure that this functionality works in concert with Bridge for Git?

**Comment by Alexandru-Dumitru** [comment]
Is this still an issue? I've tested on my side and works as expected.

**Comment by zdmullen** [comment]
Yep, it's fine now. I'm closing this.
