### ISSUE TITLE
Use VSCode internal storage (folders) to store temp files

### ISSUE THREAD

**Issue by roman-kupriyanov** [eclipse/che-che4z-explorer-for-endevor#263]
There are two types of shared folders (global & workspace level) provided by VSCode APIs (see `globalStorageUri` & `storageUri` fields of `ExtensionContext` in [the API Reference](https://code.visualstudio.com/api/references/vscode-api#ExtensionContext)).

A proposal is to reuse one of these internal folders as a temporary storage for files during Editing the Element, replacing `.e4e` workspace folder and also a necessity of having the setting to control the name of such folder.

**Comment by nickImbirev** [comment]
resolved in the https://github.com/eclipse/che-che4z-explorer-for-endevor/pull/272 (1.2.0 release)
