### ISSUE TITLE
Add an ability to cancel the testing of the Endevor Web Services URL

### ISSUE THREAD

**Issue by nickImbirev** [eclipse/che-che4z-explorer-for-endevor#268]
**AS IS:**

Right now, the user can create a new Endevor Connection in the extension UI, but when it comes to the Endevor Web Services URL specification - the user can enter some incorrect URL and hang the validation request for a while, which actually blocks the extension UI and the user flow.

**TO BE:**

There should be an ability to **cancel** the Endevor URL validation request and reenter it again (or to continue to the next Endevor connection prompt).

**Comment by roman-kupriyanov** [comment]
We have a related issue #126 😉

**Comment by nickImbirev** [comment]
resolved in the https://github.com/eclipse/che-che4z-explorer-for-endevor/pull/272 (1.2.0 release)
