### ISSUE TITLE
Log shows plain text password for profile endevor-location

### ISSUE THREAD

**Issue by cizji** [eclipse/che-che4z-explorer-for-endevor#277]
**Describe the bug**

After installing 1.2.0 I had problem with accessing Endevor, log stated full details including password. I had to remove the zowe.config.json so the Endevor Explorer read the existing profiles.

`2022-08-26T15:00:18.329Z - Inventory location instance or environment or stage number is missing for the profile endevor-location, actual value is {"host":"host.network.domain","user":"test","rejectUnauthorized":true,"password":"tset"}`.

**To Reproduce**

It does not show anymore after I had deleted the `zowe.config.json`

**Expected behavior**

The password should be replaced with "******"

**Screenshots**

**Desktop (please complete the following information):**

- OS - Windows 10
- VSCode version - 1.70.2
- Extension version - 1.2.0

**Additional context**

**Comment by uzuko001** [comment]
Hello @cizji thanks for opening this issue.
We will try address it in our next release.

**Comment by nickImbirev** [comment]
closed by https://github.com/eclipse/che-che4z-explorer-for-endevor/pull/282
