### ISSUE TITLE
Enhancement: Prefix commands with extension name

### ISSUE THREAD

**Issue by YuanboXue-Amber** [eclipse/che-che4z-explorer-for-endevor#30]
VSCode extension commands can be accessed by pressing 'F1' to open command palette, then typing the command title.

For example, for this extension, there's a command with the title 'New connection'. It can be accessed in VSCode by doing 'F1' -> type 'New connection' in the input box.

It is difficult to tell that this command actually is provided by Explorer.
Therefore I suggest adding a prefix to the command title. something like:
"Endevor-Explr: New Connection"

There are some commands that probably don't even make sense to be exposed to the command palette. For example 'browse element'. Probably wanna take those away from package.json.

**Comment by nickImbirev** [comment]
Soo, the current state is: we are only exposing a few commands into the Command Palette and I'm not sure, they are actively used (at least I'm not aware about it).

The proposal itself is really good (to have a prefix for the commands) and we are actually using it for command ids. Today, we can add some 'E4E' prefix for the commands: `Refresh Tree`, `Add a new service` and for two commands, only visible in Theia (`Accept diff changes` and `Discard diff changes`).

**Comment by nickImbirev** [comment]
@roman-kupriyanov we are gonna fix it in the upcoming release, right?

**Comment by roman-kupriyanov** [comment]
Affirmative 😃

**Comment by nickImbirev** [comment]
resolved in the https://github.com/eclipse/che-che4z-explorer-for-endevor/pull/272 (1.2.0 release)
