### ISSUE TITLE
Inconsistency on the "profile" property in the package.json file

### ISSUE THREAD

**Issue by FALLAI-Denis** [eclipse/che-che4z-explorer-for-endevor#39]
When editing the settings of the "Explorer for Endevor" extension in VS Code, an anomaly in the properties structure is reported: a "profile" property is missing.

In the package.json file, at the properties description, the "profile" property is required, but in the settings.json file it is a "profileLabel" property that is used.

![E4E profile property missing 1](https://user-images.githubusercontent.com/63861965/90952441-e7331000-e463-11ea-9ee3-f135daa62d3a.png)

![E4E profile property missing 2](https://user-images.githubusercontent.com/63861965/90952445-edc18780-e463-11ea-9ce4-e1eae153dde2.png)

![E4E profile property missing 3](https://user-images.githubusercontent.com/63861965/90952452-f31ed200-e463-11ea-9bfd-04ca112a0e6d.png)

**Comment by jellypuno** [comment]
@FALLAI-Denis  We've updated our settings and the profile property is not in v0.12.1. Is it okay to close this issue?

**Comment by FALLAI-Denis** [comment]
Ok
