### ISSUE TITLE
Compatibility with the @zowe/secure-credential-store-for-zowe-cli plugin

### ISSUE THREAD

**Issue by FALLAI-Denis** [eclipse/che-che4z-explorer-for-endevor#40]
This issue probably concerns the plugin @broadcom/endevor-for-zowe-cli.

It seems that the "Explorer for Endevor" extension is not compatible with the @zowe/secure-credential-store-for-zowe-cli plugin: when this plugin is installed, "Explorer for Endevor" manages to display the "filters" and  "maps", but fails to list the Elements.

When we uninstall the @zowe/secure-credential-store-for-zowe-cli plugin (and recreate the Endevor profile used), it becomes possible to list the Elements.

**Comment by Alexandru-Dumitru** [comment]
Hi @FALLAI-Denis,

Thanks for bringing this up. 
Just to confirm, this extension does not support profiles created by Secure Credential Store, so far. The reason being that SCS acts as another credential manager, replacing the default one which comes from `zowe/imperative` framework that writes the profiles in plain text. So, this would be more of an enhancement request to this extension. Also it has nothing to do with `@broadcom/endevor-plugin-for-zowe-cli` as that one works with SCS, because at the CLI level, this is enabled already.

> Note for implementation purposes: Zowe Explorer already works with secured profiles

**Comment by zdmullen** [comment]
@FALLAI-Denis, 

Would you like to have support for the Secure Credential Store in Explorer for Endevor?

Thanks,

Zach

**Comment by FALLAI-Denis** [comment]
Hi @zdmullen 

We want to have a secure information management solution compatible with all ZOWE plugins.
This means that in our opinion, the management of sensitive elements must be centralized in a single component, and that all plugins refer to this single component. This will allow it to be scalable and not to impose one technical solution more than another.

**Comment by FALLAI-Denis** [comment]
Still blocked at Explorer for Endevor by using Secure Credentials Store.

The zowe endevor command line works well with Secure Credentials Store.

If the extension does not quickly bring a solution to this point, we will have to give it up. It is unthinkable to use an extension that imposes clear identifiers and passwords.

**Comment by jellypuno** [comment]
@FALLAI-Denis I need more information, please help me understand the request. 

Currently in the E4E extension you can create a profile without entering a username and password. This will not save your credentials in your machine. At the same time, you can use that same profile in CLI and your credentials will be prompted.  Is this something that you are looking for? 

Or are you specifically looking for the support of SCS?  meaning that you want to use  `@zowe/secure-credential-store-for-zowe-cli` plugin as your credential manager and you want those secured profile to be loaded in the extension?

**Comment by FALLAI-Denis** [comment]
Not introducing a user / password in the zowe cli Endevor profile for the Explorer for Endevor extension to work in the presence of the Secure Credentials Storage plugin is a workaround.

This is not satisfactory.

This is indeed a problem with the Explorer for Endevor extension, then the zowe cli Endevor command line works perfectly with the Secure Credentials Store plugin.

We want the Explorer for Endevor plugin to work in the presence of the Secure Credentials Store plugin, just like all the other extensions we use, (Zowe Explorer, IBM Z Open Editor).

**Comment by jellypuno** [comment]
@FALLAI-Denis Thank you for the info. We will take a look into this.

**Comment by FALLAI-Denis** [comment]
Hi,

Explorer for Endevor still not compatible with Secure Credential Storage?

Form Explorer for Endevor v1.0.1:

```
2022-03-17T20:06:31.164Z - Unable to fetch any valid element from Endevor.
2022-03-17T20:06:31.164Z - Unable to fetch the elements from ETU/SIRIS/S9/* because of response code 16 with reason 
EWS1117I Request processed by SysID GMVS, STC WSEWSSTC - STC50844
EWS1115E Internal error in API request, please contact technical support and provide Tomcat log.
```

```
20:06:29.265 <http-nio-8180-exec-1> ERROR (c.c.e.j.EndevorSubmitSCL) [EndevorSubmitSCL - Internal error] STC: EWS1117I Request processed by SysID GMVS, STC WSEWSSTC - STC39497                                                                                         
20:06:29.265 <http-nio-8180-exec-3> ERROR (c.c.e.j.EndevorSubmitSCL) [EndevorSubmitSCL - Internal error] STC: EWS1117I Request processed by SysID GMVS, STC WSEWSSTC - STC39475                                                                                         
20:06:29.265 <http-nio-8180-exec-1> ERROR (c.c.e.j.EndevorSubmitSCL) [EndevorSubmitSCL - Internal error] com.ca.endevor.eapi.SubmitSCLRequest.createRequestBlock:76: Submit SCL request gets native error: [NATIVE ERR] Incorrect length 53 of user Id.                 
20:06:29.266 <http-nio-8180-exec-3> ERROR (c.c.e.j.EndevorSubmitSCL) [EndevorSubmitSCL - Internal error] com.ca.endevor.eapi.SubmitSCLRequest.createRequestBlock:76: Submit SCL request gets native error: [NATIVE ERR] Incorrect length 53 of user Id.                 
20:06:31.258 <http-nio-8180-exec-10> ERROR (c.c.e.j.EndevorSubmitSCL) [EndevorSubmitSCL - Internal error] STC: EWS1117I Request processed by SysID GMVS, STC WSEWSSTC - STC50843                                                                                        
20:06:31.258 <http-nio-8180-exec-2> ERROR (c.c.e.j.EndevorSubmitSCL) [EndevorSubmitSCL - Internal error] STC: EWS1117I Request processed by SysID GMVS, STC WSEWSSTC - STC50844                                                                                         
20:06:31.259 <http-nio-8180-exec-10> ERROR (c.c.e.j.EndevorSubmitSCL) [EndevorSubmitSCL - Internal error] com.ca.endevor.eapi.SubmitSCLRequest.createRequestBlock:76: Submit SCL request gets native error: [NATIVE ERR] Incorrect length 53 of user Id.                
20:06:31.259 <http-nio-8180-exec-2> ERROR (c.c.e.j.EndevorSubmitSCL) [EndevorSubmitSCL - Internal error] com.ca.endevor.eapi.SubmitSCLRequest.createRequestBlock:76: Submit SCL request gets native error: [NATIVE ERR] Incorrect length 53 of user Id.           
```      

```
zowe profiles list endevor --sc
name:     GMVS
  contents:
    host:               GMVS
    port:               8180
    user:               managed by @zowe/secure-credential-store-for-zowe-cli
    password:           managed by @zowe/secure-credential-store-for-zowe-cli
    protocol:           http
    basePath:           EndevorService/api/v2
    rejectUnauthorized: false
```

From Zowe Endevor CLI:

```
zowe  endevor list elements -i ENDEVOR --env ETU --sn 1 --sys SIRIS --sub S9 --typ COBOL* --endevor-p GMVS
[INFO] Running on host: GMVS:8180 instance: ENDEVOR
[INFO] LIST ELEMENTS executed in location: ETU/1/SIRIS/S9 on element: undefined.COBOL*
elmName    typeName envName stgNum sysName sbsName
AMAB00     COBOLP   ETU     1      SIRIS   S9
AMCSV0     COBOLP   ETU     1      SIRIS   S9
AMCSV1     COBOLP   ETU     1      SIRIS   S9
AMCSV5     COBOLP   ETU     1      SIRIS   S9
AMDATE     COBOLP   ETU     1      SIRIS   S9
AMDINA     COBOLP   ETU     1      SIRIS   S9
AMEXQI     COBOLP   ETU     1      SIRIS   S9
AMEXQR     COBOLP   ETU     1      SIRIS   S9
...
```

**Comment by nickImbirev** [comment]
Hey @FALLAI-Denis!

Yeah, regretfully, the E4E v1.0.1 still does not have a SCS (Secure Credential Store) support. I can recommend to use profiles without credentials instead, E4E will prompt you for the credentials, they will not be saved anywhere on the disk, just in memory during the VSCode session.

We investigated the ability to add a SCS support, it should not be a big deal, once it will be prioritised and moved in progress - it will be available here, in the issue.

Hope that helps

Best regards, Nikolai
