### ISSUE TITLE
Define a path for storing execution reports for endevor for zowe cli in the endevor profile

### ISSUE THREAD

**Issue by FALLAI-Denis** [eclipse/che-che4z-explorer-for-endevor#43]
This issue is for the @broadcom/endevor-for-zowe-cli plugin. In the absence of a public GitHub site for this plugin, I declare it here.

The execution reports of zowe endevor commands are stored in the current directory, and therefore probably never purged.

You should be able to declare a location for storing execution reports at the zowe endevor profile level, and even if it is possible to declare this location in an environment variable like "ZOWE_ENDEVOR_REPORTS_LOCATION".

This would allow for example to declare the temporary files folder as the storage location for Endevor execution reports, (on Windows the location% temp%).

![Endevor reports location](https://user-images.githubusercontent.com/63861965/91544898-abdf8800-e920-11ea-940d-a479b78f0f99.png)

**Comment by jellypuno** [comment]
@FALLAI-Denis Can we close this issue?

**Comment by vaughnmarshall** [comment]
Moved to Ideations site for Endevor:  https://community.broadcom.com/participate/ideation-home/viewidea?IdeationKey=5ca29aa0-882a-45c6-ad7d-a4e47d054b40
