### ISSUE TITLE
View action on Element

### ISSUE THREAD

**Issue by FALLAI-Denis** [eclipse/che-che4z-explorer-for-endevor#45]
The "Explorer for Endevor" extension provides actions "Browse Element" (in fact "PRINT ELEMENT"), and "Retrieve Element" which sets a lock at Endevor level (Signout option).

The @zowe/endevor-for-zowe-cli plugin provides a "view" command to do a "retrieve no signout".

I suggest that a "View Element" action be added to the "Explorer for Endevor" extension to allow element retrieval without setting a lock in Endevor.

**Comment by nickImbirev** [comment]
Hi Denis!

I see the point, actually, for now, the Retrieve Element feature works exactly like 'View', since we don't have upload back to Endevor workflow. We don't actually set the lock at Endevor level during current retrieving.

Does it makes sense?

**Comment by FALLAI-Denis** [comment]
@nickImbirev 

I confirm that the retrieve made from Explorer for Endevor does not "signout":

![image](https://user-images.githubusercontent.com/63861965/100908022-496fc800-34cb-11eb-811d-b9950f795d22.png)

It seemed to me that I had done tests that showed the opposite ...
So request made wrongly.

**Comment by FALLAI-Denis** [comment]
Wrong issue.
