### ISSUE TITLE
Saving connection settings in the "user" settings.json

### ISSUE THREAD

**Issue by FALLAI-Denis** [eclipse/che-che4z-explorer-for-endevor#46]
Using VS Code, by default the settings for connections to an Endevor configuration (EWS) are saved in the workspace's settings.json file, not in the user's settings.json file.

The connection settings contains information related to the user, which causes a problem when the workspace is a GIT repository: these settings are propagated to other users during GIT push / merge ...

The connections settings to an Endevor configuration should be saved in the user's settings.json file, or even differentiated between user-related settings, stored in the user's settings.json file, and context-related to Endevor settings (EWS Server), stored in the workspace settings.json file (shareable by all users).

**Comment by zdmullen** [comment]
Hey @FALLAI-Denis,

Thank you for raising this issue, and the numerous others recently. We are working on a bug related to settings.json, and will take this issue under advisement for our upcoming planning.

I did want to ask if you were interested in having a call with some folks in the team to go through your use cases for Explorer for Endevor, as well as talk about the features that we are planning for the Explorer in the near term. Feel free to send me an email at zachariah.mullen@broadcom.com if you would like that. 

Thanks!

**Comment by FALLAI-Denis** [comment]
Hi @zdmullen , 
Thank you for your interest in our requests.
I would be difficult for me to have a live call with you because I do not speak English, ("_Google translate is my friend_", not everyday...).
On the other hand, I could try to exchange with you by email or documents.
We are currently leading a project to modernize the development environment for the mainframe, based on VS Code and Zowe CLI, to address Endevor, via Git repositories, (replacing the IBM VisualAge Pacbase system, a COBOL generator, but not only, widely used in France, and no longer supported today).
We're new to all of these tools, and sometimes we can make requests that in the end may not really make sense.
Thanks.

**Comment by zdmullen** [comment]
Thanks for the response, @FALLAI-Denis!

Can you send me an email at the address I shared above? I can continue the conversation there.

**Comment by Alexandru-Dumitru** [comment]
Addressed in https://github.com/eclipse/che-che4z-explorer-for-endevor/pull/53 and available in release 0.11.0. 
@FALLAI-Denis Could you please confirm it's meeting your needs?

Thank you.

**Comment by FALLAI-Denis** [comment]
I confirm.
After removing "endevor.connections" from "workspace settings", and reconfiguring Explorer for Endevor, connection profil is now saved in "user settings".

Thanks.

**Comment by zdmullen** [comment]
Thanks for confirming, @FALLAI-Denis
