### ISSUE TITLE
Error: Workspace

### ISSUE THREAD

**Issue by jellypuno** [eclipse/che-che4z-explorer-for-endevor#47]
This error message is so vague:

![image](https://user-images.githubusercontent.com/45042840/96616836-20bcb600-1303-11eb-8453-a95cef73bf30.png)

I would like to ask for a better error message.

**Comment by zdmullen** [comment]
We're on it 👍

**Comment by Alexandru-Dumitru** [comment]
Proposing to use VS Code Welcome View instead:
https://code.visualstudio.com/api/references/contribution-points#contributes.viewsWelcome

![welcome-screen-vscode](https://user-images.githubusercontent.com/45846673/96688598-a717dd00-1381-11eb-85c3-ade2b2576f9d.PNG)

**Comment by jellypuno** [comment]
This is already implemented in v0.12.1
