### ISSUE TITLE
Fix Eslint error

### ISSUE THREAD

**Issue by Alexandru-Dumitru** [eclipse/che-che4z-explorer-for-endevor#63]
PR https://github.com/eclipse/che-che4z-explorer-for-endevor/pull/61 is switching from tslint to eslint. The rules are strict, but while implementing it, some code needed to be exluded from the rules.

This is to go back to source and fix all outstanding errors. Ideally we want to have no piece of code which is excluded. Where not possible, explanation in comments is welcomed.

**Comment by jellypuno** [comment]
This is already implemented in v0.12.1
