### ISSUE TITLE
NOTICE.md doesn't reflect current state of the project

### ISSUE THREAD

**Issue by Alexandru-Dumitru** [eclipse/che-che4z-explorer-for-endevor#64]
https://github.com/eclipse/che-che4z-explorer-for-endevor/blob/master/NOTICE.md

Third-Party Content needs to be updated as follows:
 (-) requests
(+) broadcom/endevor-for-zowe-cli
(+) zowe/imperative

**Comment by jellypuno** [comment]
This is already implemented in v0.12.1
