### ISSUE TITLE
Issue listing elements with lowercase letters or long names

### ISSUE THREAD

**Issue by MikeBauerCA** [eclipse/che-che4z-explorer-for-endevor#7]
When viewing elements, if the element name has lowercase letters or has more than eight characters, the displayed element name is altered. I opened this issue against the CA Endevor plug-in for Zowe CLI and the feedback was that they needed to use the fullElmName field instead of the elmName field. There could likely be significant synergy and code reuse between these projects. 

This issue does not occur in the Eclipse interface:
![Eclipse_Endevor](https://user-images.githubusercontent.com/35504792/69069277-37240880-09f4-11ea-8669-410874e6406b.png)

Explorer for Endevor and CA Endevor plug-in for Zowe CLI:
![image](https://user-images.githubusercontent.com/35504792/69069733-00022700-09f5-11ea-9912-ec351268b1e6.png)

**Comment by jellypuno** [comment]
@MikeBauerCA Is this issue still happening with v0.12.1?

**Comment by katelynienaber** [comment]
This one should be assigned to Roman when he has an account...

**Comment by nickImbirev** [comment]
resolved in the #272 (1.2.0 release)
