### ISSUE TITLE
There is no ability to specify Zowe location

### ISSUE THREAD

**Issue by nickImbirev** [eclipse/che-che4z-explorer-for-endevor#77]
**AS IS**
As a user, I need to install Zowe globally, not in my preferable place. 

**TO BE**
As u user, I can specify Zowe where I want to and just specify the details in the extension configuration.

**Environment:**
OS - MacOs Catalina
VS Code - 1.51.1
Endevor Explorer - 0.11.1
Zowe version - 6.24.5

**Comment by Alexandru-Dumitru** [comment]
Could you please provide more details regarding the context of this request? 
Is this regarding the location of endevor and endevor-location profiles? why would you need the ability to specify where Zowe (I assume the CLI) is installed? 

Thank you
