### ISSUE TITLE
Profiles not shared across Explorer for Endevor and CLI/requires restart of workspace in Eclipse Che

### ISSUE THREAD

**Issue by zdmullen** [eclipse/che-che4z-explorer-for-endevor#78]
There seems to be an issue that a profile created via the CLI or in the UI of Explorer for Endevor does not appear and is not available for use in the other. Please ensure that I can use one profile across both the extension and Zowe CLI in Eclipse Che.

**Comment by katelynienaber** [comment]
This one can close when [this PR](https://github.com/eclipse/che-che4z-explorer-for-endevor/pull/93) gets merged...

**Comment by Alexandru-Dumitru** [comment]
Not sure if #93 addresses this issue.

**Comment by nickImbirev** [comment]
this is not reproducible anymore
