### ISSUE TITLE
Not Showing proper lable for username while creating new profile on THEIA

### ISSUE THREAD

**Issue by deepali-hub** [eclipse/che-che4z-explorer-for-endevor#79]
Description: 
Explorer for Endvor is not showing proper lable in THEIA like when we create a new profile and on the username inputbox it shows enter url.

Steps to Reproduce issue:
1. Click on create new profile
2. Enter profile name 
3. Enter host and port (fakehost:1003)
4. Now see the username inpubox lable.

Expected Result:
It should display  proper lable for username "Enter the user name for the connection. Leave blank to not store. (Press 'Enter' to confirm your input or 'Escape' to cancel)"

Screenshot:
![image](https://user-images.githubusercontent.com/63286916/100359203-86cde480-2ff7-11eb-8abd-84ac4bf0565e.png)

**Comment by nickImbirev** [comment]
It is not reproducible anymore
