### ISSUE TITLE
Accepts hostname and port without http/https in THEIA but same action is not working in VSCode

### ISSUE THREAD

**Issue by deepali-hub** [eclipse/che-che4z-explorer-for-endevor#80]
Description:
While creating a profile on THEIA i can enter hostname and port without http/https but if i do the same on VSCode it throws an error.

Steps to reproduce issue:

1. Click on create new profile
2. Enter profile name
3. Enter host and port (fakehost:1003)

Expected result:
Behavior should be same in VSCode and THEIA

Screenshot:
From VSCODE:
![image](https://user-images.githubusercontent.com/63286916/100359818-5dfa1f00-2ff8-11eb-90ce-41530cc26958.png)

**Comment by jellypuno** [comment]
Please check the issue with port 443 as well

**Comment by nickImbirev** [comment]
So, I tested this, it is not reproducible anymore.

I will close this issue and open a new one, based on [this](https://github.com/eclipse/che-che4z-explorer-for-endevor/issues/80#issuecomment-848746062) comment
